version: "3"

services:
  # FTPSERVER START HERE!
  ftp:
    container_name: ftp
    image: matheusgoncalves/ftpserver:latest
    restart: always
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
    volumes:
      - ftphttp:/var
    environment:
      FTP_USER: "admin"
      FTP_PASS: "admin"
    networks:
      - ftpauth

  # WEBSERVER START HERE
  # apache image for testing
  http:
    container_name: apache
    image: httpd:2
    restart: always
    volumes:
      - ftphttp:/var
    networks:
      - httpauth
      - nginx

  # DB START HERE
  db:
    container_name: mongo
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db:/data/db
    networks:
      - dbauth

  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    restart: always
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx

  #auth:
  #  container_name: nginx
  #  image: nginx
  #  restart: always
  #  networks:
  #    - httpauth
  #    - ftpauth
  #    - nginx

volumes:
  ftphttp:
  dbvolume:

networks:
  ftpauth:
  httpauth:
  dbauth:
  nginx:
