version: "3"

services:
  # FTPSERVER START HERE!
  ftp:
    container_name: ftp
    image: matheusgoncalves/ftpserver:latest
    restart: always
    ports:
      - "2001:20"
      - "2101:21"
      - "47400-47470:47400-47470"
      # - "2201:22"
    volumes:
      - ftphttp:/opt
    environment:
      FTP_USER: "admin"
      FTP_PASS: "admin"
    networks:
      - ftpauth

  # WEBSERVER START HERE
  # apache image for testing
  http:
    container_name: httpserver
    image: leonerii/httpserver:v1.1
    restart: always
    volumes:
      - ftphttp:/var/www
    networks:
      - httpauth
      - nginx

  # DB START HERE
  db:
    container_name: mongo
    image: mongo:4.2-bionic
    restart: always
    volumes:
      - ./db:/data/db
      - ./dbimport.json:/opt/dbimport.json
      - ./import.sh:/docker-entrypoint-initdb.d/import.sh
    networks:
      - dbauth
    

  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    restart: always
    ports:
      - "82:80"
      - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./ssl.conf:/etc/nginx/conf.d/ssl.conf
    networks:
      - nginx

  auth:
    container_name: auth
    image: leonerii/authserver:v1.4
    restart: always
    networks:
      - httpauth
      - ftpauth
      - dbauth
      - nginx

volumes:
  ftphttp:
  dbvolume:

networks:
  ftpauth:
  httpauth:
  dbauth:
  nginx:
